"""empty message

Revision ID: 704f745e3e27
Revises: 9e7d69b47921
Create Date: 2020-05-08 07:40:14.855160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704f745e3e27'
down_revision = '9e7d69b47921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website', sa.String(length=250), nullable=True))
    op.drop_column('Venue', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('website_link', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'website')
    # ### end Alembic commands ###
